### ISSUE TITLE
Two subscribers?

### ISSUE THREAD

**Issue by rekby** [asaskevich/EventBus#12]
As I see sources - 

    func (bus *EventBus) Subscribe(topic string, fn interface{}) error {
        ...
        bus.handlers[topic] = &eventHandler{
            v, false, false, false, sync.Mutex{},
        }
        ...
    }

It bus support only one subscriber for each topic? 
If I add second subscriber it will overwrite first.

**Comment by bennAH** [comment]
Yes that is correct. You can send a pull request for the bus to support multiple subscribers

**Comment by rekby** [comment]
See the commit 
https://github.com/gaxunil/EventBus/commit/f71cc0121678ef2819822dba75b399d5cb7dcccd

I can't create pull request from other user commit (non branch - in next commit of the branch the user change the documents and library path in documents).

**Comment by bennAH** [comment]
I have run all the tests and they all pass. Will merge the changes. Thanks for your contribution

**Comment by asaskevich** [comment]
Thanks, @bennAH for merging https://github.com/gaxunil/EventBus/commit/f71cc0121678ef2819822dba75b399d5cb7dcccd and @rekby for pointing this issue, :+1:
