### ISSUE TITLE
Introduce bus interface instead of struct

### ISSUE THREAD

**Issue by mklimuk** [asaskevich/EventBus#19]
Hello,

Could we replace structs with interfaces to facilitate testing of bus-dependent services? This would also provide an elegant way to implement the network bus: it would simply be an another implementation of the interface. I'm working on a corresponding PR.
It would be useful to tag releases as well as more and more people use dependency management tools.

Cheers,
Michal

**Comment by bennAH** [comment]
Hi @mklimuk, please send a PR and update once happy. We will take a look

**Comment by bennAH** [comment]
Closing this issue - some refactoring will be planned
